### ISSUE TITLE
Resource links not saving on a Layout

### ISSUE THREAD

**Issue by justinbkay** [BeaconCMS/beacon_live_admin#103]
When saving a resource link in a Layout, it doesn't save the entry.  Just resets the form to empty.  Here's the logged output for the save action in the terminal

`Parameters: ["save", %{"layout" => %{"resource_links" => %{"0" => %{"href" => "/assets/fontawesome/css/fontawesome.css", "rel" => "stylesheet"}}}}]`

**Comment by AZholtkevych** [comment]
FYI @leandrocp
