### ISSUE TITLE
Error loading live data tab: `failed to call Beacon.Content.live_data_paths_for_site`

### ISSUE THREAD

**Issue by zachdaniel** [BeaconCMS/beacon_live_admin#147]
## Environment

OS: MacOS
Elixir/Erlang: Latest elixir/erlang versions
live_admin & beacon: fresh clone of both repositories

## Full Error

```elixir
failed to call Beacon.Content.live_data_paths_for_site(:zachdaniel_dev) for site :zachdaniel_dev on node :"core@Zachs-MacBook-Pro-2"

Got:

  Erlang error: {:exception, :undef, [{Beacon.Content, :live_data_paths_for_site, [:zachdaniel_dev], []}]}
```

**Comment by leandrocp** [comment]
This should be already fixed by https://github.com/BeaconCMS/beacon_live_admin/pull/141 - please reopen if you find that bug again. Thanks!
