### ISSUE TITLE
Fix sidebar style

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon_live_admin#148]
It should be of the same height of the page

<img width="1306" alt="Screenshot 2024-05-03 at 2 55 45 PM" src="https://github.com/BeaconCMS/beacon_live_admin/assets/36407/85a856bd-e6d7-4e9b-8211-698aa819dbeb">

**Comment by swainea** [comment]
Fix Merged: https://github.com/BeaconCMS/beacon_live_admin/pull/159/
