### ISSUE TITLE
Make site selector more visible

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon_live_admin#149]
Site selector is hard to find, it's located at the bottom/end of the left sidebar. We should move it another place to make it more visible.

<img width="1306" alt="Screenshot 2024-05-03 at 2 55 45 PM" src="https://github.com/BeaconCMS/beacon_live_admin/assets/36407/e06e6e24-6308-4e57-be4a-c5d249c0690e">

**Comment by brzpegasus** [comment]
Closing as duplicate of #148.
