### ISSUE TITLE
Setup github actions

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon_live_admin#15]
Similar to https://github.com/BeaconCMS/beacon/blob/main/.github/workflows/elixir.yml

**Comment by karthikmurali60** [comment]
@leandrocp can i work on this issue? Could you please provide more details about the required github action ?

**Comment by leandrocp** [comment]
Hi @karthikmurali60 

> can i work on this issue?

Sure :)

> Could you please provide more details about the required github action ?

We don't use credo nor dialyzer yet in this repo so those checks aren't necessary. A database connection is necessary for Beacon sites defined at https://github.com/BeaconCMS/beacon_live_admin/blob/36680c9631bf09f90ac3a56159fc01f28939114f/test/support/cluster.ex#L100-L112 and this check https://github.com/BeaconCMS/beacon/blob/fcbb5b5dea75d17db96aef78fb1b9988e1a0bffe/.github/workflows/elixir.yml#L127 should be enabled in this repo.

**Comment by leandrocp** [comment]
btw @karthikmurali60 feel free to ask if that that's not clear :)

**Comment by leandrocp** [comment]
Closed by https://github.com/BeaconCMS/beacon_live_admin/pull/47
