### ISSUE TITLE
Fix element selection on page builder

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon_live_admin#154]
https://github.com/BeaconCMS/beacon_live_admin/issues/111#issuecomment-2052654302

**Comment by cibernox** [comment]
https://github.com/BeaconCMS/beacon_live_admin/assets/265339/944e3040-f65f-443c-9e79-a00814ae0235

I think this may have been fixed already. At least it does look easy to use IMO

**Comment by cibernox** [comment]
Cynthia confirmed the fix. Closing this one.
