### ISSUE TITLE
Display a "X" or trash icon on the element boundary when hovering it to allow deleting the element

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon_live_admin#193]
Currently it's possible to delete elements from the page by clicking on the element, expanding the Delete section on the right sidebar, clicking Delete, and confirming. We want to optimize this whole process since deleting elements is an operation executed very often.

The idea we want to explore is adding some icon on the boundary of the element either when you hover or select such element to have quick access to the Delete operation, eg:

<img width="850" alt="Screenshot 2024-08-02 at 10 16 47 AM" src="https://github.com/user-attachments/assets/5d6c8cbe-ebc8-43ae-8ec8-016d8427f956">

**Comment by cibernox** [comment]
Personally I'd probably show the button to delete it not when hovering but when it's selected. That goes along the pattern i'm implementing in which, for drag and drop, I show some floating buttons next to the selected element to move it.

**Comment by leandrocp** [comment]
> Personally I'd probably show the button to delete it not when hovering but when it's selected. That goes along the pattern i'm implementing in which, for drag and drop, I show some floating buttons next to the selected element to move it.

That makes sense and is the behavior that other tools are taking as well.
