### ISSUE TITLE
Media Library: Filtering by asset type

### ISSUE THREAD

**Issue by AZholtkevych** [BeaconCMS/beacon_live_admin#20]
Add filtering of assets by type to `BeaconWeb.Admin.MediaLibraryLive.Index`. Filter by all types available https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/lib/beacon/media_library/asset.ex#L9

**Comment by leandrocp** [comment]
See https://github.com/BeaconCMS/beacon_live_admin/issues/89
