### ISSUE TITLE
Failing to save changes after making changes on the visual editor

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon_live_admin#226]
It doesn't happen every time but to reproduce it you can make some changes on the visual editor then hit Save Changes. Sometimes it will display the success alert but the actual content was not saved. That may happen due to malformed template that we're not validating or some race condition, still needs more investigation.

**Comment by cibernox** [comment]
If someone can find specific reproduction steps I'll dig into this

**Comment by leandrocp** [comment]
> If someone can find specific reproduction steps I'll dig into this

@cibernox I was not able to reproduce locally but it was reported to happen on our staging env. I don't think the Visual Editor component itself is causing it, but would be helpful if you can help find the root cause.
