### ISSUE TITLE
Preview changes before publishing

### ISSUE THREAD

**Issue by kwando** [BeaconCMS/beacon_live_admin#81]
The UX when authoring layouts and pages is not that great currently. In order to make changes I have to first press "save changes" followed by a "publish" and then reload my browser window to see the changes I did. 

It would be much nicer to be able to preview the changes while editing without having to publish and refresh.

Some other random feedback:
- Some high level docs describing the core concepts would be nice
- Make the demo app a little fancier, it is so barebones right now that you almost question if it is working or not  when seeing it fro the firs time :)

**Comment by cibernox** [comment]
I am working on that feature actually. It’s very much my main focus right now.

**Comment by kwando** [comment]
I love to hear that is coming :)

**Comment by leandrocp** [comment]
Hey @kwando thanks for the feedback!

Like @cibernox said, he's working on that feature on this PR https://github.com/BeaconCMS/beacon_live_admin/pull/80

Docs are being done at https://github.com/BeaconCMS/beacon_live_admin/pull/69 and the demo issue is tracked here https://github.com/BeaconCMS/beacon/issues/226 although we didn't start working on it yet.

I'm closing this issue for now but feel free to add more comments.

/cc @AZholtkevych

**Comment by kwando** [comment]
I just built my own little crazy thing, in essence I can "checkout" a site to a folder. Putting layouts in `<mysite>/layouts/<uuid>.heex`, `<mysite>/pages/<uuid>.heex` etc.
I then utilize the `:file_system` hex package to listen for changes made to files in the filesystem and just call the Beacon APIs to update and publish the changes.

```elixir
  def handle_change(["layouts", filename], path) do
    layout_id = Path.basename(filename, Path.extname(filename))

    case Beacon.Content.get_layout(layout_id) do
      nil ->
        Logger.warning("Layout #{layout_id} not found")

      layout ->
        layout
        |> Beacon.Content.change_layout(%{template: File.read!(path)})
        |> Beacon.Repo.update!()
        |> Beacon.Content.publish_layout()

        Logger.info("Updated layout #{layout_id}")
    end
  en
```

It is crude, litters the database with useless snapshots and is not really a preview of the changes since they are auto published... but I can use my own editor and I thought it was a fun experiment :) There is probably something I can broadcast also so the PageLive-thingy will refresh.. but yeah better to wait for the "real deal" you guys are building.

**Comment by leandrocp** [comment]
@kwando that's a nice experiment, it looks like a file-system based router https://nextjs.org/docs/app/building-your-application/routing/defining-routes

I considered implementing a similar feature to ease the development of new pages but it encourages more deployments, which is something we want to avoid, so I couldn't find a good balance yet. In the meantime we're improving the editor along with the page builder to deliver a better UX https://github.com/BeaconCMS/live_monaco_editor

With that said, Beacon is extensible so it's really cool to see such experiments that could result in a real feature in the future. Thanks!
